# Generated by Django 5.2.17 on 2026-09-04 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingestion_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('csv', 'CSV File Upload'), ('api', 'External API'), ('database', 'External Database'), ('manual', 'Manual Entry')], max_length=50)),
                ('source_reference', models.CharField(help_text='File path, API endpoint, or database connection string', max_length=500)),
                ('data_type', models.CharField(help_text='Type of data ingested: sales, inventory, product_master, etc.', max_length=100)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_inserted', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='running', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Detailed error records per row/batch')),
                ('trigger_type', models.CharField(default='manual', help_text='manual, scheduled, api', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingestion_logs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('location_code', models.CharField(db_index=True, max_length=50)),
                ('transaction_date', models.DateField(db_index=True)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_promotion', models.BooleanField(default=False)),
                ('promotion_code', models.CharField(blank=True, max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to='ingestion.ingestionlog')),
            ],
            options={
                'db_table': 'sales_transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['sku', 'location_code', 'transaction_date'], name='sales_trans_sku_4820c9_idx'), models.Index(fields=['transaction_date'], name='sales_trans_transac_61b229_idx'), models.Index(fields=['sku', 'transaction_date'], name='sales_trans_sku_daaaa2_idx')],
            },
        ),
    ]
