# Generated by Django 5.2.17 on 2026-09-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandHistoryAggregated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('aggregation_level', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('period_start_date', models.DateField(db_index=True)),
                ('period_end_date', models.DateField()),
                ('total_demand', models.IntegerField(default=0, help_text='Total units sold in this period')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('promotion_flag', models.BooleanField(default=False, help_text='Whether promotion was active in this period')),
                ('stockout_flag', models.BooleanField(default=False, help_text='Whether stockout occurred in this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='forecasting.location')),
            ],
            options={
                'db_table': 'demand_history_aggregated',
                'ordering': ['-period_start_date'],
                'indexes': [models.Index(fields=['sku', 'location', 'aggregation_level', 'period_start_date'], name='demand_hist_sku_428b73_idx'), models.Index(fields=['period_start_date'], name='demand_hist_period__77e672_idx')],
                'unique_together': {('sku', 'location', 'aggregation_level', 'period_start_date')},
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('feature_date', models.DateField(db_index=True)),
                ('lag_1', models.IntegerField(blank=True, help_text='Demand 1 week ago', null=True)),
                ('lag_2', models.IntegerField(blank=True, null=True)),
                ('lag_4', models.IntegerField(blank=True, null=True)),
                ('lag_12', models.IntegerField(blank=True, null=True)),
                ('lag_52', models.IntegerField(blank=True, help_text='Demand 1 year ago', null=True)),
                ('rolling_mean_7d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rolling_mean_14d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rolling_mean_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rolling_std_7d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rolling_std_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('week_of_year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('promotion_active', models.BooleanField(default=False)),
                ('days_since_promotion', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_features', to='forecasting.location')),
            ],
            options={
                'db_table': 'time_series_features',
                'ordering': ['-feature_date'],
                'indexes': [models.Index(fields=['sku', 'location', 'feature_date'], name='time_series_sku_c2c9a4_idx'), models.Index(fields=['feature_date'], name='time_series_feature_bbe913_idx')],
                'unique_together': {('sku', 'location', 'feature_date')},
            },
        ),
    ]
