# Generated by Django 5.2.17 on 2026-09-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('stock_on_hand', models.IntegerField(default=0, help_text='Current available sellable stock')),
                ('stock_in_transit', models.IntegerField(default=0, help_text='Stock in transit from suppliers/warehouses')),
                ('reorder_point', models.IntegerField(default=0, help_text='Calculated reorder trigger point')),
                ('safety_stock', models.IntegerField(default=0, help_text='Buffer stock for demand spikes / lead time variability')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='forecasting.location')),
            ],
            options={
                'db_table': 'inventory_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['sku', 'location', 'snapshot_date'], name='inventory_s_sku_3f4fa0_idx'), models.Index(fields=['snapshot_date'], name='inventory_s_snapsho_c3bf17_idx')],
                'unique_together': {('sku', 'location', 'snapshot_date')},
            },
        ),
    ]
