import React, { useState, useEffect } from 'react';
import { ConfidenceChart } from '../components/ConfidenceChart';
import {
  Trophy,
  AlertTriangle,
  TrendingUp,
  ShieldCheck,
  ArrowUpRight
} from 'lucide-react';
import APIService from '../services/api';

export const ExecutiveOverview = ({ onNavigate, onOpenRetrain }) => {
  const [forecasts, setForecasts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedSku, setSelectedSku] = useState('BEV-001');

  useEffect(() => {
    const fetchOverviewData = async () => {
      setLoading(true);
      const res = await APIService.getForecasts({ sku: selectedSku, location: 1, horizon: 14 });
      setForecasts(res.data);
      setLoading(false);
    };
    fetchOverviewData();
  }, [selectedSku]);

  const totalDemand14d = forecasts.reduce((acc, f) => acc + (f.predicted_demand || 0), 0);

  const kpis = [
    { label: 'Champion model WAPE', value: '12.19%', delta: '-4.17% vs baseline', deltaType: 'positive' },
    { label: '90% PICP band coverage', value: '92.40%', delta: '+2.40% over target', deltaType: 'positive' },
    { label: '14-day forecast volume', value: `${totalDemand14d.toLocaleString()} units`, delta: '+8.4% week-over-week', deltaType: 'positive' },
    { label: 'Critical stockout risk', value: '3 SKUs', delta: 'Action required', deltaType: 'negative' },
  ];

  return (
    <div className="space-y-6">
      {/* Status strip */}
      <div className="panel border-l-[3px] border-l-signal-amber p-4 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="w-1.5 h-1.5 bg-signal-amber shrink-0" />
            <h2 className="text-sm font-display font-bold text-paper">Production AI forecasting online</h2>
            <span className="text-[10px] font-medium text-signal-amber">Champion: HistGBDT v1.8</span>
          </div>
          <p className="text-xs text-paper-muted mt-1">
            14-day horizon forward projection active across 8 SKUs &amp; 4 fulfillment centers.
          </p>
        </div>

        <div className="flex items-center gap-2 w-full md:w-auto">
          <button
            onClick={() => onNavigate('forecasts')}
            className="flex-1 md:flex-none px-3.5 py-2 bg-graphite-800 hover:bg-graphite-850 border border-hairline text-xs font-medium text-paper transition flex items-center justify-center gap-1.5"
          >
            <span>Explore forecasts</span>
            <ArrowUpRight className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={onOpenRetrain}
            className="flex-1 md:flex-none px-3.5 py-2 bg-signal-amber hover:bg-signal-amber/90 text-xs font-semibold text-graphite-950 transition flex items-center justify-center gap-1.5"
          >
            <Trophy className="w-3.5 h-3.5" />
            <span>Retrain models</span>
          </button>
        </div>
      </div>

      {/* KPI ledger row */}
      <div className="panel grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 divide-y sm:divide-y-0 divide-hairline lg:divide-x">
        {kpis.map((kpi) => (
          <div key={kpi.label} className="p-4">
            <p className="text-xs text-paper-muted">{kpi.label}</p>
            <p className="text-2xl font-display font-bold text-paper mt-1">{kpi.value}</p>
            <p className={`text-[11px] mt-1 ${kpi.deltaType === 'positive' ? 'text-status-healthy' : 'text-status-critical'}`}>
              {kpi.delta}
            </p>
          </div>
        ))}
      </div>

      {/* Main Chart Section: Demand Curve with 90% Confidence Bounds */}
      <div className="panel p-5 space-y-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-hairline pb-4">
          <div>
            <h3 className="text-sm font-semibold text-paper flex items-center gap-2">
              <span>Projected demand curve with 90% confidence envelope</span>
              <span className="px-1.5 py-0.5 bg-graphite-800 text-paper-dim text-[10px] font-mono">
                14 days
              </span>
            </h3>
            <p className="text-xs text-paper-muted mt-0.5">
              Shaded band reflects the 5th to 95th percentile uncertainty interval generated by the GBDT ensemble.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs text-paper-muted">SKU</span>
            <select
              value={selectedSku}
              onChange={(e) => setSelectedSku(e.target.value)}
              className="px-3 py-1.5 bg-graphite-950 border border-hairline text-xs text-paper font-medium focus:outline-none focus:border-signal-amber transition"
            >
              <option value="BEV-001">BEV-001 - Sparkling Tonic (330ml)</option>
              <option value="BEV-002">BEV-002 - Cold Brew Nitro (250ml)</option>
              <option value="EL-001">EL-001 - Wireless Keyboard</option>
              <option value="EL-002">EL-002 - USB-C GaN Charger 65W</option>
              <option value="HOM-001">HOM-001 - Bamboo Towel Set</option>
              <option value="PER-001">PER-001 - Facial Cleanser</option>
              <option value="PER-002">PER-002 - Mineral Sunscreen SPF 50+</option>
            </select>
          </div>
        </div>

        <ConfidenceChart
          forecasts={forecasts}
          skuLabel={selectedSku}
          locationLabel="Central Fulfillment Hub"
        />
      </div>

      {/* Two Column Section: Model Tournament Leaderboard Snapshot & Stockout Alerts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Tournament Snapshot */}
        <div className="panel p-5 space-y-3">
          <div className="flex items-center justify-between pb-3 border-b border-hairline">
            <h4 className="text-xs font-semibold text-paper flex items-center gap-2">
              <Trophy className="w-4 h-4 text-signal-amber" />
              <span>Model tournament benchmark</span>
            </h4>
            <button
              onClick={() => onNavigate('leaderboard')}
              className="text-xs text-signal-amber hover:text-paper font-medium transition"
            >
              Full leaderboard
            </button>
          </div>

          <div className="divide-y divide-hairline">
            <div className="py-2.5 border-l-[3px] border-l-signal-amber pl-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-paper text-xs flex items-center gap-1.5">
                  HistGradientBoosting (GBDT)
                  <span className="text-[10px] text-signal-amber font-medium">Champion</span>
                </p>
                <p className="text-[11px] text-paper-muted mt-0.5">18 feature lag &amp; cyclic pipeline</p>
              </div>
              <div className="text-right">
                <p className="font-mono font-semibold text-signal-amber text-sm">12.19% WAPE</p>
                <p className="text-[10px] text-paper-muted font-mono">RMSE: 5.68</p>
              </div>
            </div>

            <div className="py-2.5 pl-3 flex items-center justify-between">
              <div>
                <p className="font-medium text-paper text-xs">Stacked deep MLP neural net</p>
                <p className="text-[11px] text-paper-muted mt-0.5">[64, 32] ReLU architecture</p>
              </div>
              <div className="text-right">
                <p className="font-mono font-semibold text-paper text-sm">12.64% WAPE</p>
                <p className="text-[10px] text-paper-muted font-mono">RMSE: 6.09</p>
              </div>
            </div>

            <div className="py-2.5 pl-3 flex items-center justify-between">
              <div>
                <p className="font-medium text-paper-muted text-xs">Weighted moving average (14d)</p>
                <p className="text-[11px] text-paper-muted mt-0.5">Heuristic baseline</p>
              </div>
              <div className="text-right">
                <p className="font-mono font-semibold text-paper-muted text-sm">16.36% WAPE</p>
                <p className="text-[10px] text-paper-muted font-mono">RMSE: 8.05</p>
              </div>
            </div>
          </div>
        </div>

        {/* Urgent Inventory Risks */}
        <div className="panel p-5 space-y-3">
          <div className="flex items-center justify-between pb-3 border-b border-hairline">
            <h4 className="text-xs font-semibold text-paper flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-status-critical" />
              <span>Critical inventory stockout risks</span>
            </h4>
            <button
              onClick={() => onNavigate('inventory')}
              className="text-xs text-status-critical hover:text-paper font-medium transition"
            >
              View all alerts
            </button>
          </div>

          <div className="divide-y divide-hairline">
            <div className="py-2.5 border-l-[3px] border-l-status-critical pl-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-paper text-xs">BEV-001 (Sparkling Tonic)</p>
                <p className="text-[11px] text-paper-muted mt-0.5">Central Hub &middot; 2.1 days of supply</p>
              </div>
              <div className="text-right">
                <span className="text-[10px] font-semibold text-status-critical">CRITICAL</span>
                <p className="text-[10px] text-paper-muted mt-1 font-mono">Order 600 units</p>
              </div>
            </div>

            <div className="py-2.5 border-l-[3px] border-l-status-critical pl-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-paper text-xs">PER-002 (Mineral Sunscreen SPF 50+)</p>
                <p className="text-[11px] text-paper-muted mt-0.5">Southern Hub &middot; 1.8 days of supply</p>
              </div>
              <div className="text-right">
                <span className="text-[10px] font-semibold text-status-critical">CRITICAL</span>
                <p className="text-[10px] text-paper-muted mt-1 font-mono">Order 400 units</p>
              </div>
            </div>

            <div className="py-2.5 border-l-[3px] border-l-status-warning pl-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-paper text-xs">EL-002 (GaN Charger 65W)</p>
                <p className="text-[11px] text-paper-muted mt-0.5">West Coast DC &middot; 4.3 days of supply</p>
              </div>
              <div className="text-right">
                <span className="text-[10px] font-semibold text-status-warning">WARNING</span>
                <p className="text-[10px] text-paper-muted mt-1 font-mono">Order 350 units</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
