# Generated by Django 5.2.17 on 2026-09-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('store', 'Retail Store'), ('warehouse', 'Regional Warehouse'), ('dc', 'Distribution Center')], default='store', max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('capacity_units', models.IntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['location_code'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=255)),
                ('model_architecture', models.CharField(choices=[('lstm', 'Stacked LSTM Deep Neural Network'), ('gru', 'Gated Recurrent Unit (GRU)'), ('holt_winters', 'Holt-Winters Exponential Smoothing'), ('moving_average', 'Weighted Rolling Moving Average')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('data_start_date', models.DateField(blank=True, null=True)),
                ('data_end_date', models.DateField(blank=True, null=True)),
                ('train_test_split_date', models.DateField(blank=True, null=True)),
                ('mape', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Percentage Error (%)', max_digits=8, null=True)),
                ('wape', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted Absolute Percentage Error (%)', max_digits=8, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, help_text='Root Mean Squared Error', max_digits=10, null=True)),
                ('mae', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Error', max_digits=10, null=True)),
                ('picp', models.DecimalField(blank=True, decimal_places=2, help_text='Prediction Interval Coverage Probability (%)', max_digits=6, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('is_champion', models.BooleanField(default=False)),
                ('model_artifact_path', models.CharField(blank=True, max_length=500)),
                ('triggered_by', models.CharField(default='system', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('training_start_time', models.DateTimeField(auto_now_add=True)),
                ('training_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_training_runs',
                'ordering': ['-training_start_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='forecasting.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('forecast_date', models.DateField(db_index=True)),
                ('forecast_horizon', models.IntegerField(help_text='Forecast horizon in weeks or days')),
                ('predicted_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasting.location')),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='forecasting.modeltrainingrun')),
            ],
            options={
                'db_table': 'forecasts',
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lead_time_days', models.IntegerField(default=14, help_text='Supplier lead time in days')),
                ('min_order_qty', models.IntegerField(default=10, help_text='Minimum order quantity for replenishment')),
                ('safety_stock_days', models.IntegerField(default=7, help_text='Target safety stock days of supply')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Active'), ('phase_out', 'Phase Out'), ('new_launch', 'New Launch'), ('discontinued', 'Discontinued')], default='active', max_length=50)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='forecasting.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAccuracyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('absolute_error', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_error', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_records', to='forecasting.forecast')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_records', to='forecasting.location')),
            ],
            options={
                'db_table': 'forecast_accuracy_records',
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['sku', 'location', 'forecast_date'], name='forecast_ac_sku_591aec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['sku', 'location', 'forecast_date'], name='forecasts_sku_ccba3e_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['forecast_date', 'forecast_horizon'], name='forecasts_forecas_dae0a6_idx'),
        ),
    ]
